export default [
  {
    id: 1,
    name: "Amarjeet Gnarly",
    role: "Founder and Global President",
    img: "https://www.gnarlytroop.org/Bulletproof/founder.jpg",
    href: "",
  },
  {
    id: 2,
    name: "Prof Group Captain O P Sharma",
    role: "Chief Advisor",
    img: "https://www.gnarlytroop.org/img/4.jpg",
    href: "",
  },
  {
    id: 3,
    name: "Wing Commander K H N Singh",
    role: "Gnarly Commander",
    img: "https://www.gnarlytroop.org/img/2.jpg",
    href: "",
  },
  {
    id: 4,
    name: "Shri Mahendra R Rajput",
    role: "Executive Committee Member",
    img: "https://www.gnarlytroop.org/img/Mahendra-K-Rajput.jpg",
    href: "",
  },
  {
    id: 5,
    name: "Dr. Bhaskar Swami",
    role: "Executive Committee Member",
    img: "https://www.gnarlytroop.org/Bulletproof/bhashkar-swami.jpeg",
    href: "",
  },
  {
    id: 6,
    name: "Brigadier (Dr.) Sanjeev Chopra",
    role: "Executive Association Director",
    img: "https://www.gnarlytroop.org/Bulletproof/Sanjeev-Chopra.jpg",
    href: "",
  },
  {
    id: 7,
    name: "Hansmukh Patel",
    role: "Executive Committee Member",
    img: "https://www.gnarlytroop.org/Bulletproof/Hansmukh-Patel.jpg",
    href: "",
  },
  {
    id: 8,
    name: "Prof. Manoj Vajpayee",
    role: "Global Program Development Chair",
    img: "https://www.gnarlytroop.org/Bulletproof/Manoj-Vajpayee.jpg",
    href: "",
  },
  {
    id: 9,
    name: "Shri Kamleshbhai Shastri ji Maharaj",
    role: "Envoy of Unity and Culture",
    img: "https://www.gnarlytroop.org/Bulletproof/Kamleshbhai-Shastri.jpg",
    href: "",
  },
  {
    id: 10,
    name: "Rishav Chaturvedi",
    role: "Petrol Leader",
    img: "https://www.gnarlytroop.org/Bulletproof/Rishav-Chaturvedi.jpg",
    href: "",
  },
];
